Repository WildCodeSchool/lyon-js-react-march21-g2-p2, pull requests merged in 2021-04, with the labels that each got.

#1 Init
  .gitignore
  README.md
  README.old.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: WIP

#3 Create issue_template
  .github/issue_template.md
Labels: Ready for prod

#39 Update issue templates
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: Ready for prod

#52 38 create json
  package-lock.json
  package.json
  src/assets/movieList.json
  src/components/HomePage.js
  src/components/MovieCard.css
  src/components/MovieCard.js
  src/components/MoviesPage.js
  src/components/card.css
  src/components/card.js
Labels: Ready for validation

#66 58 carousel
  package-lock.json
  package.json
  src/components/ConvertGenreIdToName.js
  src/components/FilteringBar.css
  src/components/FilteringBar.js
  src/components/MovieCarousel.css
  src/components/MovieCarousel.js
  src/components/MovieList.js
  src/screens/HomePage.css
  src/screens/HomePage.js
  src/screens/MoviePage.js
  yarn.lock
Labels: Ready for prod

#68 13 info section
  src/components/Header.js
  src/components/Main.js
  src/components/MovieCarousel.js
  src/components/MovieInfos.js
  src/screens/DisplayPage.js
Labels: Ready for prod

#55 #22 filtering bar
  .env.sample
  .gitignore
  package-lock.json
  package.json
  src/components/ConvertGenreIdToName.js
  src/components/FilteringBar.css
  src/components/FilteringBar.js
  src/components/MovieList.js
  src/screens/HomePage.js
  src/screens/MoviePage.js
  yarn.lock
Labels: Fixed - ready for prod, Ready for prod

#67 15 favorite icon
  .gitignore
  package-lock.json
  package.json
  src/components/MovieCard.js
  yarn.lock
Labels: Fixed - ready for prod, Ready for prod

#73 10 acces details from posters
  package.json
  public/index.html
  src/components/Header.js
  src/components/Main.js
  src/components/MovieInfos.js
  src/components/MovieList.js
  src/components/UsersComment.js
  src/screens/DetailsPage.js
  src/screens/DisplayPage.js
  yarn.lock
Labels: Ready for prod

#75 70 send email
  src/App.css
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.js
  src/components/Main.js
  src/components/MovieCard.js
  src/components/MovieCarousel.js
  src/components/MovieList.js
  src/screens/ContactPage.js
  src/screens/FavoritePage.css
Labels: Ready for prod

#74 02 search input
  .env.sample
  public/favicon.ico
  public/index.html
  src/App.css
  src/assets/movieList.json
  src/components/ConvertGenreIdToName.js
  src/components/FilteringBar.css
  src/components/FilteringBar.js
  src/components/Footer.js
  src/components/Header.js
  src/components/MovieCard.js
  src/components/MovieCarousel.js
  src/components/MovieList.js
  src/components/SearchBox.js
  src/screens/ContactPage.js
  src/screens/FavoritePage.css
  src/screens/HomePage.js
  src/screens/MoviePage.js
Labels: Ready for prod

#77 17 favorite page
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/issue_template.md
  package.json
  src/components/Header.js
  src/components/MovieCard.js
  src/components/ReviewList.js
  src/screens/FavoritePage.js
  yarn.lock
Labels: Ready for prod
